### ISSUE TITLE
Remove transition animation?

### ISSUE THREAD

**Issue by carolynz** [kenmoore/sketch-artboard#1]
(From issue I accidentally opened on another project of yours)

Is there a way to turn off the transition when flipping between artboards, for easy artboard comparison?

**Comment by kenmoore** [comment]
Hi Carolyn, in Preferences on the Canvas tab uncheck "Animate Zoom" and you should be good to go.  I'm investigating ways to determine if that preference is checked so I can alert the user to turn it off -- so thanks for raising that point!
