### ISSUE TITLE
Change shortcut

### ISSUE THREAD

**Issue by ralts00** [kenmoore/sketch-artboard#11]
Currently uses the same shortcut as a [plugin](https://github.com/Freakland/sketch-browser-preview) that I use a lot a day.
Please :)

**Comment by kenmoore** [comment]
Sorry, as you're the only one to request this (and as it's VERY difficult to find keyboard shortcuts that don't conflict with something else), I'll leave it to you to customize your app shortcuts using the System Preferences.
