### ISSUE TITLE
Next / Previous Artboard On Unfocused Window

### ISSUE THREAD

**Issue by joshmtucker** [kenmoore/sketch-artboard#3]
Hi Ken,

First, thanks for this plugin - it's been great! One issue I've been encountering. Sometimes if I have multiple windows open, using the shortcuts to go Next or Previous Artboard will work on one of the unfocused windows I have open in Sketch, not the one I am currently focused on/using. 

Thanks!

**Comment by kenmoore** [comment]
Hi Josh,

Thanks for the report.  There's  been a bug in Sketch 3.4, 3.4.1 and 3.4.2 where some plugins target the non-foreground window, and it's surfacing with this plugin.  I've just checked in a patch, could you get the updated plugin and confirm that it's working?  I hear from the folks at Bohemian that the bug has been fixed but that won't help much until 3.4.3 is out.

Thanks much
Ken

**Comment by joshmtucker** [comment]
Awesome, thanks for the explanation and plugin update. Latest version seems to address the issue, super appreciate it!
