### ISSUE TITLE
Switch Next/Previous functionality

### ISSUE THREAD

**Issue by patrickplaggenborg** [kenmoore/sketch-artboard#4]
I love your plugin. It helps me mimic app interactions, using artboards for states like Photoshop Layer Comps did.

Your plugin jumps from artboard to artboard bottom-to-top.
However, when exporting artboards to PDF, Sketch orders them top-to-bottom.

Would it make sense to switch your 'Next Artboard' and 'Previous Artboard' functionality and keyboard shortcuts to match Sketch artboard order?

**Comment by kenmoore** [comment]
Hi Patrick, I'm glad you like the plugin, and thanks for the suggestion.  I can't figure out why, but all other plugins seem to treat the order as bottom-to-top, e.g. Numberize (https://github.com/bomberstudios/sketch-commands/tree/master/Sketch%20Commands.sketchplugin/Contents/Sketch/Numberize) and other Next/Previous Artboard plugins.  I always found it counterintuitive but have learned to live with it.  I would just worry that if I change my plugin then it might cause more conflict.  What would be best is some toggle to allow specifying which direction is up... I'll keep that in mind, though I doubt I'll have time to address it anytime soon.

Ken

**Comment by patrickplaggenborg** [comment]
Yeah a toggle would be nice to not cause conflict with existing users.

As a workaround, I switched the keyboard shortcuts around with custom keyboard shortcuts in System Preferences.

**Comment by username1290** [comment]
FYI in latest Sketch (3.9beta) one can select export preferences (Top-bottom, left-right, etc)
