### ISSUE TITLE
Deselect All

### ISSUE THREAD

**Issue by patrickplaggenborg** [kenmoore/sketch-artboard#5]
I use the plugin to do presentations as well.

During design, and especially during presentations, the artboard selection handles are quite annoying.

Right now, after pressing a keyboard shortcut to switch artboard, I need to press ESC to deselect and hide the selection handles.

Would it be possible to include a 'Deselect All' command after a switch?

**Comment by kenmoore** [comment]
Hi Patrick, I looked into this -- it's just one line of code but I think not seeing the current artboard selected in the layers panel would make it hard to use in the course of everyday work. If you want to edit your local version, just add this line after the zoomToFitRect call in each of the .js files:

  doc.currentPage().deselectAllLayers();

Hope that's helpful!

**Comment by kenmoore** [comment]
Or even better, I just discovered that Sketch now supports next/previous artboard natively with Fn+Left arrow / Right arrow.  It doesn't zoom to fit width, however, but if all your slides are the same size that could be a good solution.

**Comment by patrickplaggenborg** [comment]
Nice, thanks! Didn't know about Fn + arrow keys. Respects zoom level but doesn't change selection so that's helpful, especially during presentations.
