### ISSUE TITLE
Overlap makes plugin stop cycling

### ISSUE THREAD

**Issue by username1290** [kenmoore/sketch-artboard#6]
Hi, can't get it to work in 3.8.3

**Comment by kenmoore** [comment]
Hi there, I just tried it with 3.8.3 and a fresh install of the plugins and all works as expected.  Maybe there's a conflict with some other plugin you have installed?  Sorry, not sure what else to advise.

**Comment by username1290** [comment]
thx, will check

**Comment by username1290** [comment]
Found the issue:
It doesn't like **artboards overlapped**.
To make sure no plugins interferred I cleaned up my plugins folder, and still experienced the issue.

This screenshot is an example where the plugin will stop working at some time in the process if 2 artboards share a bit of vertical **overlap** (shown in the red area):
![screen shot 2016-07-05 at 1 03 40 pm](https://cloud.githubusercontent.com/assets/2784323/16594642/f004297a-42b0-11e6-9dc9-2ebe6b5ed574.png)

If they stop overlapping (i.e. Artboard 3 is moved further to the right), the plugin starts working again:

![screen shot 2016-07-05 at 1 04 11 pm](https://cloud.githubusercontent.com/assets/2784323/16594657/fbd997b2-42b0-11e6-91f6-01dd5346e5ef.png)

**Plugins works again, no overlap**

**Comment by kenmoore** [comment]
Hi Sogen, can you send me a Sketch file with the not working case?  I've tried creating the overlapping you're referring to and everything is still working as expected here.  Thanks.

**Comment by username1290** [comment]
Sure:
[Untitled.sketch.zip](https://github.com/kenmoore/sketch-artboard/files/348342/Untitled.sketch.zip)

**Comment by kenmoore** [comment]
Ok, not sure what to say but it's working for me.  I can invoke Next Artboard / Previous Artboard and it switches between them.  I wonder whether there might not be some bizarre plugin conflict, you might try temporarily moving all your other plugins into a different folder to see if that doesn't fix things.  Otherwise I'd have to chalk it up to a Sketch bug -- the same file in the same version of Sketch on 2 different computers should not behave any differently.

**Comment by username1290** [comment]
hm, that's odd..
To make sure no plugins interferred I cleaned up my plugins folder, and still experienced the issue.
if it helps I'm using **Yosemite**,

**Comment by kenmoore** [comment]
Hm, ok... I'm using El Capitan, so maybe that's the bit that's causing the
different behaviors, as odd as that seems.  Let me reach out to one of my
contacts at Bohemian Coding and see if he has any idea what's up.
