### ISSUE TITLE
Plugin stopped working since Sketch dropped Legacy Plugin support

### ISSUE THREAD

**Issue by patrickplaggenborg** [kenmoore/sketch-artboard#7]
Sketch 43 dropped support for 'Legacy Plugins':
http://sketchplugins.com/d/63-sketch-43-will-drop-support-for-legacy-plugins

sketch-artboard was still a legacy plugin.

Is there a way to convert it to their newer plugin type that works in the latest version of Sketch?

**Comment by patrickplaggenborg** [comment]
Apparently, plugins now need to be 'bundled':
http://developer.sketchapp.com/introduction/plugin-bundles/

Would it be possible to create a bundle like that with the current plugin files?

**Comment by kenmoore** [comment]
Hi Patrick, I just updated the plugin to use the new bundle format -- please give it a try and confirm that it works as expected!  Thanks

**Comment by patrickplaggenborg** [comment]
Works as expected, thanks!
